export const GET_ALL_ANIMALS = 'GET_ALL_ANIMALS'

export const SUCCESS_GET_ALL_ANIMALS = 'SUCCESS_GET_ALL_ANIMALS'

export const FAILED_GET_ALL_ANIMALS = 'FAILED_GET_ALL_ANIMALS'

export const GET_ANIMAL_DETAILS = 'GET_ANIMAL_DETAILS'

export const SUCCESS_GET_ANIMAL_DETAILS = 'SUCCESS_GET_ANIMAL_DETAILS'

export const FAILED_GET_ANIMAL_DETAILS = 'FAILED_GET_ANIMAL_DETAILS'

export const ADD_ANIMAL = 'ADD_ANIMAL'

export const SUCCESS_ADD_ANIMAL = 'SUCCESS_ADD_ANIMAL'

export const FAILED_ADD_ANIMAL = 'FAILED_ADD_ANIMAL'
